### PR TITLE
incorrect query syntax causes api to return 404 status when not using client auth.

### PR DESCRIPTION
**Pull request by joates**
should _always_ use client auth but since it is possible to not use any auth, need to check for this.

``` shell
curl 'https://api.github.com/repos/dominictarr/feedopensource/collaborators&per_page=100'
{
  "message": "Not Found",
  "documentation_url": "http://developer.github.com/v3"
}
```

### CODE REVIEW

**Comment by joates** [comment]
> enable override default host with config setting.

there may be a _cleaner_ way to inject the config.host setting into the RegExp than this..
(but it works and it makes it easier for me to continue QA testing).

**Comment by joates** [comment]
> [bugfix] open tasks are counted as completed tasks (incorrectly)

tested -> [here](https://xtco.in/iteration/xtcrypto/funding-project/1HcPJnizgeEUTQ6UC2brE2sHjHQKyWy8E8)

**Comment by joates** [comment]
> tested -> [here](https://xtco.in/iteration/xtcrypto/funding-project/1HcPJnizgeEUTQ6UC2brE2sHjHQKyWy8E8)

the link _shows that it does work without escaping_ (the caveat is that it **must be the final character in the group**)

althought if it is explicitly escaped then the hyphen can be anywhere in the group and it will not be interpreted as part of a range.

**Comment by dominictarr** [comment]
ah, okay. better to escape it I think.

**Comment by dominictarr** [comment]
this is fixed now.

**Pull request merged**
